### ISSUE TITLE
Sugestão de readme

### ISSUE THREAD

**Issue by williamWHC** [leopaixaoneto/MottuTest#3]
Bom dia Leo!
Deis de já, parabéns pelo projeto.

Sugestão é adicionar a versão utilizada, ex versão Node.js x.x.x
![image](https://github.com/leopaixaoneto/MottuTest/assets/43853142/b0566d57-cae5-4076-b5c1-5f8c0fc679b6)

**Comment by leopaixaoneto** [comment]
Melhorado o Readme.md 

Obrigado pelas dicas!
