### ISSUE TITLE
Atualização de readme

### ISSUE THREAD

**Issue by williamWHC** [leopaixaoneto/MottuTest#4]
![image](https://github.com/leopaixaoneto/MottuTest/assets/43853142/f893db8d-d6ad-45bc-a552-1723658ef9c8)

Exemplo apresentação de foto de perfil  no final do readme.

Código => 
![image](https://github.com/leopaixaoneto/MottuTest/assets/43853142/0729d2d7-006a-4d6b-8490-9d098e8eac3b)

**Comment by leopaixaoneto** [comment]
Melhorado o Readme.md 

Obrigado pelas dicas!
